version: '3.1'

services:

  db2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./logs/audit:/data/mysql/auditlogs
    ports:
      - 127.0.0.1:13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

